name: Mirror from Codeberg

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up remote for Codeberg
      run: |
        git remote add codeberg https://codeberg.org/superseriousbusiness/gotosocial.git
        git fetch codeberg

    - name: Merge and push
      run: |
        git merge codeberg/main --allow-unrelated-histories -m "Mirror from Codeberg"
        git push origin HEAD:main
