name: Mirror from Codeberg

on:
  schedule:
    - cron: '17 */2 * * *' # Runs at 17 minutes past the hour, every 2 hours

  workflow_dispatch:

permissions:
  contents: write  # 添加这行，授予写入权限

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Set up remote for Codeberg
      run: |
        git remote add codeberg https://codeberg.org/superseriousbusiness/gotosocial.git
        git fetch codeberg

    - name: Merge and push
      run: |
        git merge codeberg/main --allow-unrelated-histories -m "Mirror from Codeberg"
        git push origin HEAD:main
